version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    networks:
      - dev-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=messengeruser
      - POSTGRES_PASSWORD=messengerpassword
      - POSTGRES_DB=messengerdb

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
