# Generated by Django 4.2.4 on 2023-09-05 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default=None, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$')]),
            preserve_default=False,
        ),
    ]
